version: '3.7'
services:

  # MongoDB replica set
  mongo1:
    image: mongo:latest
    container_name: mongo1
    networks:
      net:
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 30001:30001
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"mongo1:30001\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 10s

  jaeger:
    image: jaegertracing/all-in-one:1.39
    container_name: jaeger
    networks:
      - net
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "4317:4317"
      #      - "4318:4318"
      - "9411:9411"
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
      - "COLLECTOR_OTLP_ENABLED=true"

  ## WebSocket servers
  http-server:
    image: my-repo/http-server:1.0-SNAPSHOT
    ports:
      - "8001:8000"
      - "8005:8005"
      - "9010:9010"
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "document-streaming-app"
    depends_on:
      - mongo1
      - document-storage-service
      - jaeger
    networks:
      - net
    environment:
      - "MONGO_URL=mongodb://mongo1:30001/?replicaSet=my-replica-set"
      - "DOCUMENT_STORAGE_SERVICE_URL=document-storage-service:9000"
      - "PORT=8000"
      - "JAEGER_ENDPOINT=http://jaeger:4317"
      - "HOST=0.0.0.0"


  ## Document storage service
  document-storage-service:
    image: my-repo/document-storage-service:1.0-SNAPSHOT
    ports:
      - "9000:9000"
      - "8006:8005"
      - "9011:9010"
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "document-storage-service"
    depends_on:
      - mongo1
      - jaeger
    networks:
      - net
    environment:
      - "MONGO_URL=mongodb://mongo1:30001/?replicaSet=my-replica-set"
      - "SERVER_PORT=9000"
      - "JAEGER_ENDPOINT=http://jaeger:4317"

networks:
  net:

volumes:
  setup:
  elasticsearch:
  prom_data:
