version: "3.3"
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.crt:/etc/nginx/certs/localhost.crt
      - ./localhost-privateKey.key:/etc/nginx/certs/localhost-privateKey.key
    networks:
      - net
    depends_on:
      - http-server
    ports:
      - "8000:80"
      - "443:443"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - net

  http-server:
    image: my-repo/http-server:1.0-SNAPSHOT
    restart: always
    depends_on:
      - mongodb
    networks:
      - net
    environment:
      - "MONGO_URL=mongodb://mongodb:27017"
      - "PORT=8000"
      - "HOST=0.0.0.0"

networks:
  net: