version: '3.7'
services:

  kurento:
    image: kurento/kurento-media-server:7.0.0
    container_name: kurento
    networks:
      net:
    ports:
      - "8888:8888/tcp"

  jaeger:
    image: jaegertracing/all-in-one:1.39
    container_name: jaeger
    networks:
      - net
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "4317:4317"
      - "9411:9411"
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
      - "COLLECTOR_OTLP_ENABLED=true"

  ## WebSocket server
  websocket-calling-app:
    image: my-repo/websocket-calling-server:1.0-SNAPSHOT
    ports:
      - "8002:8000"
      - "8007:8005"
      - "9012:9010"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "websocket-calling-app"
    depends_on:
      - jaeger
      - kurento
    networks:
      - net
    environment:
      - "KURENTO_URI=ws://kurento:8888/kurento"
      - "PORT=8000"
      - "JAEGER_ENDPOINT=http://jaeger:4317"
      - "HOST=0.0.0.0"
networks:
  net: